### ISSUE TITLE
Пользователь может создать подпику на появление байка определённого семейства

### ISSUE THREAD

**Issue by esemi** [Eira/canyon-notifier#33]
DOD
---
 - юзер может подписаться на появление байков в каталоге в определённом семействе
 - новая команда описана в ридми бота

**Comment by Eira** [comment]
1.  у каждой подписки индивид id
2.  создать ключ в ктором хранится список всех айдишек подписок
3.  берем список айдишек
4.  перебираем эти значения и получаем объекты подписок
5.  в объектах подписок находим нужные имена байков
6.  и берем id и отправляем ему сообщение
