### ISSUE TITLE
Зарегистрировать нового бота

### ISSUE THREAD

**Issue by esemi** [Eira/canyon-notifier#7]
DOD
---
- [x] Боты ищутся в телеграме
- [x] В переменных репозитория сохранён токен бота для продакшена
- [x] В репозитории сохранён токен бота для локальной версии

TODO
---
- [x] [Регистрируем нового бота](https://core.telegram.org/bots#3-how-do-i-create-a-bot) для продакшена
- [x] Сохраняем токен бота в [секретах репозитория](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)
- [x] Повторяем процедуру для бота для локальной отладки
- [x] Сохраняем его токен в ридми в инструкцию для локального окружения

**Comment by Eira** [comment]
Done
